spring:
  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

business:
  allcredit:
    url: http://localhost/business/search/allcredit
  crefia:
    url: http://localhost/business/search/crefia
  hometax:
    url: http://localhost/business/search/hometax

